services:
  postgres:
    image: postgres:14.19-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/etc/todolistpostgres
volumes:
  postgres-data: